



DROP TABLE IF EXISTS `ecs_reagent_dict`;
CREATE TABLE `ecs_reagent_dict` (
`id`  smallint(5) unsigned NOT NULL auto_increment,
`enfield`  varchar(50) NOT NULL default '',
`cnfield`  varchar(50) NOT NULL default '',
  PRIMARY KEY  (`id`)
)  ENGINE=innodb;

INSERT INTO `ecs_reagent_dict` (`enfield`, `cnfield`) VALUES
('reagent_casid',                           'CAS号'),
('reagent_cnname',                          '中文名称'),
('reagent_cnalias',                         '中文别名'),
('reagent_enname',                          '英文名称'),
('reagent_enalias',                         '英文别名'),
('reagent_mdlno',                           'MDL号'),
('reagent_ec_no',                           'EC号'),
('reagent_molecularformula',                '经验分子式（希尔表示法）'),
('reagent_molecularweight',                 '分子量'),
('reagent_molecularimage',                  '分子图片'),
('reagent_molfile',                         'mol文件'),
('reagent_generaldesc',                     '一般描述'),
('reagent_use',                             '用途'),
('reagent_storage',                         '储存'),
('reagent_shape',                           '形状'),
('reagent_color',                           '颜色'),
('reagent_smell',                           '气味'),
('reagent_odorthreshold',                   '气味临界值'),
('reagent_phval',                           'pH值'),
('reagent_meltingfreezingpoint',            '熔点/凝固点'),
('reagent_boilpointrange',                  '起始沸点和沸程'),
('reagent_flashpoint',                      '闪点'),
('reagent_refractiveindex',                 '折光率'),
('reagent_Opticalrotation',                 '旋光度'),
('reagent_evaporaterate',                   '蒸发速率'),
('reagent_flammability',                    '可燃性(固体,气体)'),
('reagent_explosive_upper',                 '爆炸上限[%(V/V)]'),
('reagent_explosive_lower',                 '爆炸下限[%(V/V)]'),
('reagent_vapor_pressure',                  '蒸气压'),
('reagent_density',                         '密度'),
('reagent_relative_vapour_density',         '相对蒸气密度'),
('reagent_dissolved',                       '溶解性/水溶性'),
('reagent_water_partitioncoeff_logrth',     '辛醇/水分配系数的对数值'),
('reagent_self_ignition_temperature',       '自燃温度（℃/℉）'),
('reagent_decomposition_temperature',       '分解温度'),
('reagent_critical_temperature',            '临界温度(℃)'),
('reagent_critical_pressure',               '临界压力（MPa）'),
('reagent_viscosity',                       '粘度'),
('reagent_sensitivity',                     '敏感性'),
('reagent_damage_code',                     '危害类型编码（GHS）'),
('reagent_damage_code_pictograms',          '危害类型编码（GHS）所对应的象形图'),
('reagent_signal_words',                    '信号词'),
('reagent_danger_state',                    '危险声明'),
('reagent_caution_state',                   '警示性声明'),
('reagent_hazard_code',                     '危害码[Hazard symbol(s)]'),
('reagent_risk_state',                      '风险声明(R)'),
('reagent_security_state',                  '安全声明(S)'),
('reagent_un_code',                         '联合国编码(UN)'),
('reagent_pollution_index',                 '德国无公害指标（WGK）'),
('reagent_customs_code',                    '海关编码（HS）')

DROP TABLE IF EXISTS `ecs_reagent_info`;
CREATE TABLE `ecs_reagent_info` (
`reagent_casid`  char(30) NOT NULL default '',
`reagent_cnname`  varchar(200) NOT NULL default '',
`reagent_cnalias`  varchar(400) NOT NULL default '',
`reagent_enname`  varchar(200) NOT NULL default '',
`reagent_enalias`  varchar(400) NOT NULL default '',
`reagent_mdlno`  varchar(100) NOT NULL default '',
`reagent_ec_no`  varchar(100) NOT NULL default '',
`reagent_molecularformula`  varchar(100) NOT NULL default '',
`reagent_molecularweight`  varchar(100) NOT NULL default '',
`reagent_molecularimage`  varchar(100) NOT NULL default '',
`reagent_molfile`  varchar(100) NOT NULL default '',
`reagent_generaldesc`  varchar(500) NOT NULL default '',
`reagent_use`  varchar(100) NOT NULL default '',
`reagent_storage`  varchar(100) NOT NULL default '',
`reagent_shape`  varchar(100) NOT NULL default '',
`reagent_color`  varchar(100) NOT NULL default '',
`reagent_smell`  varchar(100) NOT NULL default '',
`reagent_odorthreshold`  varchar(100) NOT NULL default '',
`reagent_phval`  varchar(100) NOT NULL default '',
`reagent_meltingfreezingpoint`  varchar(100) NOT NULL default '',
`reagent_boilpointrange`  varchar(100) NOT NULL default '',
`reagent_flashpoint`  varchar(100) NOT NULL default '',
`reagent_refractiveindex`  varchar(100) NOT NULL default '',
`reagent_Opticalrotation`  varchar(100) NOT NULL default '',
`reagent_evaporaterate`  varchar(100) NOT NULL default '',
`reagent_flammability`  varchar(100) NOT NULL default '',
`reagent_explosive_upper`  varchar(100) NOT NULL default '',
`reagent_explosive_lower`  varchar(100) NOT NULL default '',
`reagent_vapor_pressure`  varchar(100) NOT NULL default '',
`reagent_density`  varchar(100) NOT NULL default '',
`reagent_relative_vapour_density`  varchar(100) NOT NULL default '',
`reagent_dissolved`  varchar(100) NOT NULL default '',
`reagent_water_partitioncoeff_logrth`  varchar(100) NOT NULL default '',
`reagent_self_ignition_temperature`  varchar(100) NOT NULL default '',
`reagent_decomposition_temperature`  varchar(100) NOT NULL default '',
`reagent_critical_temperature`  varchar(100) NOT NULL default '',
`reagent_critical_pressure`  varchar(100) NOT NULL default '',
`reagent_viscosity`  varchar(100) NOT NULL default '',
`reagent_sensitivity`  varchar(100) NOT NULL default '',
`reagent_damage_code`  varchar(100) NOT NULL default '',
`reagent_damage_code_pictograms`  varchar(100) NOT NULL default '',
`reagent_signal_words`  varchar(100) NOT NULL default '',
`reagent_danger_state`  varchar(100) NOT NULL default '',
`reagent_caution_state`  varchar(100) NOT NULL default '',
`reagent_hazard_code`  varchar(100) NOT NULL default '',
`reagent_risk_state`  varchar(100) NOT NULL default '',
`reagent_security_state`  varchar(100) NOT NULL default '',
`reagent_un_code`  varchar(100) NOT NULL default '',
`reagent_pollution_index`  varchar(100) NOT NULL default '',
`reagent_customs_code`  varchar(100) NOT NULL default '',
  PRIMARY KEY  (`reagent_casid`)
)  ENGINE=innodb;

